[proxy]
host = "mc.hypixel.net"
version = "1.8.9"
port = 25565

[settings]
prefix = "/"

[modules]
ezBypass = true
noChat = false
wonkyText = false

[commands]
chatReport = true
reload = true
test = true